# Generated by Django 5.1.6 on 2025-02-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('uername', models.CharField(max_length=200)),
                ('mobilenum', models.BigIntegerField()),
                ('password', models.CharField(max_length=100)),
                ('cpassword', models.CharField(max_length=200)),
            ],
        ),
    ]
