# Generated by Django 5.1.6 on 2025-02-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='todoapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todotitel', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Not started', 'Not started'), ('IN progeress', 'IN progeress'), ('completed', 'completed')], max_length=100)),
                ('due', models.TextField()),
            ],
        ),
    ]
