# Generated by Django 5.1.6 on 2025-02-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_todoapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Not started', 'Not started'), ('In progress', 'In progress'), ('Completed', 'Completed')], default='Not started', max_length=20)),
                ('due_date', models.DateField()),
            ],
        ),
    ]
